package com.bailian.entity;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ActivityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public ActivityExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andActIdIsNull() {
			addCriterion("ACT_ID is null");
			return (Criteria) this;
		}

		public Criteria andActIdIsNotNull() {
			addCriterion("ACT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andActIdEqualTo(Long value) {
			addCriterion("ACT_ID =", value, "actId");
			return (Criteria) this;
		}

		public Criteria andActIdNotEqualTo(Long value) {
			addCriterion("ACT_ID <>", value, "actId");
			return (Criteria) this;
		}

		public Criteria andActIdGreaterThan(Long value) {
			addCriterion("ACT_ID >", value, "actId");
			return (Criteria) this;
		}

		public Criteria andActIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ACT_ID >=", value, "actId");
			return (Criteria) this;
		}

		public Criteria andActIdLessThan(Long value) {
			addCriterion("ACT_ID <", value, "actId");
			return (Criteria) this;
		}

		public Criteria andActIdLessThanOrEqualTo(Long value) {
			addCriterion("ACT_ID <=", value, "actId");
			return (Criteria) this;
		}

		public Criteria andActIdIn(List<Long> values) {
			addCriterion("ACT_ID in", values, "actId");
			return (Criteria) this;
		}

		public Criteria andActIdNotIn(List<Long> values) {
			addCriterion("ACT_ID not in", values, "actId");
			return (Criteria) this;
		}

		public Criteria andActIdBetween(Long value1, Long value2) {
			addCriterion("ACT_ID between", value1, value2, "actId");
			return (Criteria) this;
		}

		public Criteria andActIdNotBetween(Long value1, Long value2) {
			addCriterion("ACT_ID not between", value1, value2, "actId");
			return (Criteria) this;
		}

		public Criteria andActNameIsNull() {
			addCriterion("ACT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andActNameIsNotNull() {
			addCriterion("ACT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andActNameEqualTo(String value) {
			addCriterion("ACT_NAME =", value, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameNotEqualTo(String value) {
			addCriterion("ACT_NAME <>", value, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameGreaterThan(String value) {
			addCriterion("ACT_NAME >", value, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameGreaterThanOrEqualTo(String value) {
			addCriterion("ACT_NAME >=", value, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameLessThan(String value) {
			addCriterion("ACT_NAME <", value, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameLessThanOrEqualTo(String value) {
			addCriterion("ACT_NAME <=", value, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameLike(String value) {
			addCriterion("ACT_NAME like", value, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameNotLike(String value) {
			addCriterion("ACT_NAME not like", value, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameIn(List<String> values) {
			addCriterion("ACT_NAME in", values, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameNotIn(List<String> values) {
			addCriterion("ACT_NAME not in", values, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameBetween(String value1, String value2) {
			addCriterion("ACT_NAME between", value1, value2, "actName");
			return (Criteria) this;
		}

		public Criteria andActNameNotBetween(String value1, String value2) {
			addCriterion("ACT_NAME not between", value1, value2, "actName");
			return (Criteria) this;
		}

		public Criteria andActDescIsNull() {
			addCriterion("ACT_DESC is null");
			return (Criteria) this;
		}

		public Criteria andActDescIsNotNull() {
			addCriterion("ACT_DESC is not null");
			return (Criteria) this;
		}

		public Criteria andActDescEqualTo(String value) {
			addCriterion("ACT_DESC =", value, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescNotEqualTo(String value) {
			addCriterion("ACT_DESC <>", value, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescGreaterThan(String value) {
			addCriterion("ACT_DESC >", value, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescGreaterThanOrEqualTo(String value) {
			addCriterion("ACT_DESC >=", value, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescLessThan(String value) {
			addCriterion("ACT_DESC <", value, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescLessThanOrEqualTo(String value) {
			addCriterion("ACT_DESC <=", value, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescLike(String value) {
			addCriterion("ACT_DESC like", value, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescNotLike(String value) {
			addCriterion("ACT_DESC not like", value, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescIn(List<String> values) {
			addCriterion("ACT_DESC in", values, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescNotIn(List<String> values) {
			addCriterion("ACT_DESC not in", values, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescBetween(String value1, String value2) {
			addCriterion("ACT_DESC between", value1, value2, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActDescNotBetween(String value1, String value2) {
			addCriterion("ACT_DESC not between", value1, value2, "actDesc");
			return (Criteria) this;
		}

		public Criteria andActPicIsNull() {
			addCriterion("ACT_PIC is null");
			return (Criteria) this;
		}

		public Criteria andActPicIsNotNull() {
			addCriterion("ACT_PIC is not null");
			return (Criteria) this;
		}

		public Criteria andActPicEqualTo(String value) {
			addCriterion("ACT_PIC =", value, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicNotEqualTo(String value) {
			addCriterion("ACT_PIC <>", value, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicGreaterThan(String value) {
			addCriterion("ACT_PIC >", value, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicGreaterThanOrEqualTo(String value) {
			addCriterion("ACT_PIC >=", value, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicLessThan(String value) {
			addCriterion("ACT_PIC <", value, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicLessThanOrEqualTo(String value) {
			addCriterion("ACT_PIC <=", value, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicLike(String value) {
			addCriterion("ACT_PIC like", value, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicNotLike(String value) {
			addCriterion("ACT_PIC not like", value, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicIn(List<String> values) {
			addCriterion("ACT_PIC in", values, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicNotIn(List<String> values) {
			addCriterion("ACT_PIC not in", values, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicBetween(String value1, String value2) {
			addCriterion("ACT_PIC between", value1, value2, "actPic");
			return (Criteria) this;
		}

		public Criteria andActPicNotBetween(String value1, String value2) {
			addCriterion("ACT_PIC not between", value1, value2, "actPic");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("START_TIME is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("START_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Timestamp value) {
			addCriterion("START_TIME =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Timestamp value) {
			addCriterion("START_TIME <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Timestamp value) {
			addCriterion("START_TIME >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Timestamp value) {
			addCriterion("START_TIME >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Timestamp value) {
			addCriterion("START_TIME <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Timestamp value) {
			addCriterion("START_TIME <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Timestamp> values) {
			addCriterion("START_TIME in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Timestamp> values) {
			addCriterion("START_TIME not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Timestamp value1, Timestamp value2) {
			addCriterion("START_TIME between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Timestamp value1,
				Timestamp value2) {
			addCriterion("START_TIME not between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("END_TIME is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("END_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Timestamp value) {
			addCriterion("END_TIME =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Timestamp value) {
			addCriterion("END_TIME <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Timestamp value) {
			addCriterion("END_TIME >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Timestamp value) {
			addCriterion("END_TIME >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Timestamp value) {
			addCriterion("END_TIME <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Timestamp value) {
			addCriterion("END_TIME <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Timestamp> values) {
			addCriterion("END_TIME in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Timestamp> values) {
			addCriterion("END_TIME not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Timestamp value1, Timestamp value2) {
			addCriterion("END_TIME between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Timestamp value1, Timestamp value2) {
			addCriterion("END_TIME not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Timestamp value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Timestamp value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Timestamp value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Timestamp value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Timestamp> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Timestamp> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Timestamp value1,
				Timestamp value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Timestamp value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Timestamp value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Timestamp value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Timestamp value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Timestamp value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Timestamp value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Timestamp> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Timestamp> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Timestamp value1, Timestamp value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Timestamp value1,
				Timestamp value2) {
			addCriterion("UPDATE_TIME not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andHotSaleIsNull() {
			addCriterion("HOT_SALE is null");
			return (Criteria) this;
		}

		public Criteria andHotSaleIsNotNull() {
			addCriterion("HOT_SALE is not null");
			return (Criteria) this;
		}

		public Criteria andHotSaleEqualTo(String value) {
			addCriterion("HOT_SALE =", value, "hotSale");
			return (Criteria) this;
		}

		public Criteria andHotSaleNotEqualTo(String value) {
			addCriterion("HOT_SALE <>", value, "hotSale");
			return (Criteria) this;
		}

		public Criteria andHotSaleGreaterThan(String value) {
			addCriterion("HOT_SALE >", value, "hotSale");
			return (Criteria) this;
		}

		public Criteria andHotSaleGreaterThanOrEqualTo(String value) {
			addCriterion("HOT_SALE >=", value, "hotSale");
			return (Criteria) this;
		}

		public Criteria andHotSaleLessThan(String value) {
			addCriterion("HOT_SALE <", value, "hotSale");
			return (Criteria) this;
		}

		public Criteria andHotSaleLessThanOrEqualTo(String value) {
			addCriterion("HOT_SALE <=", value, "hotSale");
			return (Criteria) this;
		}

		public Criteria andHotSaleIn(List<String> values) {
			addCriterion("HOT_SALE in", values, "hotSale");
			return (Criteria) this;
		}

		public Criteria andHotSaleNotIn(List<String> values) {
			addCriterion("HOT_SALE not in", values, "hotSale");
			return (Criteria) this;
		}

		public Criteria andHotSaleBetween(String value1, String value2) {
			addCriterion("HOT_SALE between", value1, value2, "hotSale");
			return (Criteria) this;
		}

		public Criteria andHotSaleNotBetween(String value1, String value2) {
			addCriterion("HOT_SALE not between", value1, value2, "hotSale");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNull() {
			addCriterion("PRIORITY is null");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNotNull() {
			addCriterion("PRIORITY is not null");
			return (Criteria) this;
		}

		public Criteria andPriorityEqualTo(Long value) {
			addCriterion("PRIORITY =", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotEqualTo(Long value) {
			addCriterion("PRIORITY <>", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThan(Long value) {
			addCriterion("PRIORITY >", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThanOrEqualTo(Long value) {
			addCriterion("PRIORITY >=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThan(Long value) {
			addCriterion("PRIORITY <", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThanOrEqualTo(Long value) {
			addCriterion("PRIORITY <=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityIn(List<Long> values) {
			addCriterion("PRIORITY in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotIn(List<Long> values) {
			addCriterion("PRIORITY not in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityBetween(Long value1, Long value2) {
			addCriterion("PRIORITY between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotBetween(Long value1, Long value2) {
			addCriterion("PRIORITY not between", value1, value2, "priority");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table T_ACTIVITY
	 * @mbggenerated  Mon May 22 20:17:18 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated do_not_delete_during_merge Mon May 22 20:03:32 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}