package com.bailian.entity;

import java.sql.Timestamp;

public class ActivityDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACTIVITY_DETAIL.DETAIL_ID
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    private Long detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACTIVITY_DETAIL.ACT_ID
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    private Long actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACTIVITY_DETAIL.GOODS_ID
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACTIVITY_DETAIL.ORDER_SEC
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    private Long orderSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACTIVITY_DETAIL.PERCENT
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    private Long percent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ACTIVITY_DETAIL.CREATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    private Timestamp createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACTIVITY_DETAIL.DETAIL_ID
     *
     * @return the value of T_ACTIVITY_DETAIL.DETAIL_ID
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public Long getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACTIVITY_DETAIL.DETAIL_ID
     *
     * @param detailId the value for T_ACTIVITY_DETAIL.DETAIL_ID
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACTIVITY_DETAIL.ACT_ID
     *
     * @return the value of T_ACTIVITY_DETAIL.ACT_ID
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public Long getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACTIVITY_DETAIL.ACT_ID
     *
     * @param actId the value for T_ACTIVITY_DETAIL.ACT_ID
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public void setActId(Long actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACTIVITY_DETAIL.GOODS_ID
     *
     * @return the value of T_ACTIVITY_DETAIL.GOODS_ID
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACTIVITY_DETAIL.GOODS_ID
     *
     * @param goodsId the value for T_ACTIVITY_DETAIL.GOODS_ID
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACTIVITY_DETAIL.ORDER_SEC
     *
     * @return the value of T_ACTIVITY_DETAIL.ORDER_SEC
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public Long getOrderSec() {
        return orderSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACTIVITY_DETAIL.ORDER_SEC
     *
     * @param orderSec the value for T_ACTIVITY_DETAIL.ORDER_SEC
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public void setOrderSec(Long orderSec) {
        this.orderSec = orderSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACTIVITY_DETAIL.PERCENT
     *
     * @return the value of T_ACTIVITY_DETAIL.PERCENT
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public Long getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACTIVITY_DETAIL.PERCENT
     *
     * @param percent the value for T_ACTIVITY_DETAIL.PERCENT
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public void setPercent(Long percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ACTIVITY_DETAIL.CREATE_TIME
     *
     * @return the value of T_ACTIVITY_DETAIL.CREATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ACTIVITY_DETAIL.CREATE_TIME
     *
     * @param createTime the value for T_ACTIVITY_DETAIL.CREATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:35 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }
}