package com.bailian.entity;

import java.sql.Timestamp;

public class AddressInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address_info.ADD_ID
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    private Long addId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address_info.MEMBER_ID
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address_info.NAME
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address_info.MOBILE
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address_info.ADD_INFO
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    private String addInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address_info.IS_DEFAULT
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    private Long isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address_info.CREATE_TIME
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address_info.UPDATE_TIME
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address_info.ADD_ID
     *
     * @return the value of t_address_info.ADD_ID
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public Long getAddId() {
        return addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address_info.ADD_ID
     *
     * @param addId the value for t_address_info.ADD_ID
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public void setAddId(Long addId) {
        this.addId = addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address_info.MEMBER_ID
     *
     * @return the value of t_address_info.MEMBER_ID
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address_info.MEMBER_ID
     *
     * @param memberId the value for t_address_info.MEMBER_ID
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address_info.NAME
     *
     * @return the value of t_address_info.NAME
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address_info.NAME
     *
     * @param name the value for t_address_info.NAME
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address_info.MOBILE
     *
     * @return the value of t_address_info.MOBILE
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address_info.MOBILE
     *
     * @param mobile the value for t_address_info.MOBILE
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address_info.ADD_INFO
     *
     * @return the value of t_address_info.ADD_INFO
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public String getAddInfo() {
        return addInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address_info.ADD_INFO
     *
     * @param addInfo the value for t_address_info.ADD_INFO
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public void setAddInfo(String addInfo) {
        this.addInfo = addInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address_info.IS_DEFAULT
     *
     * @return the value of t_address_info.IS_DEFAULT
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public Long getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address_info.IS_DEFAULT
     *
     * @param isDefault the value for t_address_info.IS_DEFAULT
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public void setIsDefault(Long isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address_info.CREATE_TIME
     *
     * @return the value of t_address_info.CREATE_TIME
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address_info.CREATE_TIME
     *
     * @param createTime the value for t_address_info.CREATE_TIME
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address_info.UPDATE_TIME
     *
     * @return the value of t_address_info.UPDATE_TIME
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address_info.UPDATE_TIME
     *
     * @param updateTime the value for t_address_info.UPDATE_TIME
     *
     * @mbggenerated Thu Jun 22 21:57:40 CST 2017
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}