package com.bailian.entity;

import java.sql.Timestamp;

public class AwardsRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AWARDS_RECORD.ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AWARDS_RECORD.MEMBER_ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AWARDS_RECORD.ACT_ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    private Long actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AWARDS_RECORD.GOODS_ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AWARDS_RECORD.STATUS
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AWARDS_RECORD.CREATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_AWARDS_RECORD.USE_TIME
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    private Timestamp useTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AWARDS_RECORD.ID
     *
     * @return the value of T_AWARDS_RECORD.ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AWARDS_RECORD.ID
     *
     * @param id the value for T_AWARDS_RECORD.ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AWARDS_RECORD.MEMBER_ID
     *
     * @return the value of T_AWARDS_RECORD.MEMBER_ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AWARDS_RECORD.MEMBER_ID
     *
     * @param memberId the value for T_AWARDS_RECORD.MEMBER_ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AWARDS_RECORD.ACT_ID
     *
     * @return the value of T_AWARDS_RECORD.ACT_ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public Long getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AWARDS_RECORD.ACT_ID
     *
     * @param actId the value for T_AWARDS_RECORD.ACT_ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public void setActId(Long actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AWARDS_RECORD.GOODS_ID
     *
     * @return the value of T_AWARDS_RECORD.GOODS_ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AWARDS_RECORD.GOODS_ID
     *
     * @param goodsId the value for T_AWARDS_RECORD.GOODS_ID
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AWARDS_RECORD.STATUS
     *
     * @return the value of T_AWARDS_RECORD.STATUS
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AWARDS_RECORD.STATUS
     *
     * @param status the value for T_AWARDS_RECORD.STATUS
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AWARDS_RECORD.CREATE_TIME
     *
     * @return the value of T_AWARDS_RECORD.CREATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AWARDS_RECORD.CREATE_TIME
     *
     * @param createTime the value for T_AWARDS_RECORD.CREATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_AWARDS_RECORD.USE_TIME
     *
     * @return the value of T_AWARDS_RECORD.USE_TIME
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public Timestamp getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_AWARDS_RECORD.USE_TIME
     *
     * @param useTime the value for T_AWARDS_RECORD.USE_TIME
     *
     * @mbggenerated Mon May 22 20:03:28 CST 2017
     */
    public void setUseTime(Timestamp useTime) {
        this.useTime = useTime;
    }
}