package com.bailian.entity;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class BannerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public BannerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBanIdIsNull() {
            addCriterion("BAN_ID is null");
            return (Criteria) this;
        }

        public Criteria andBanIdIsNotNull() {
            addCriterion("BAN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBanIdEqualTo(Long value) {
            addCriterion("BAN_ID =", value, "banId");
            return (Criteria) this;
        }

        public Criteria andBanIdNotEqualTo(Long value) {
            addCriterion("BAN_ID <>", value, "banId");
            return (Criteria) this;
        }

        public Criteria andBanIdGreaterThan(Long value) {
            addCriterion("BAN_ID >", value, "banId");
            return (Criteria) this;
        }

        public Criteria andBanIdGreaterThanOrEqualTo(Long value) {
            addCriterion("BAN_ID >=", value, "banId");
            return (Criteria) this;
        }

        public Criteria andBanIdLessThan(Long value) {
            addCriterion("BAN_ID <", value, "banId");
            return (Criteria) this;
        }

        public Criteria andBanIdLessThanOrEqualTo(Long value) {
            addCriterion("BAN_ID <=", value, "banId");
            return (Criteria) this;
        }

        public Criteria andBanIdIn(List<Long> values) {
            addCriterion("BAN_ID in", values, "banId");
            return (Criteria) this;
        }

        public Criteria andBanIdNotIn(List<Long> values) {
            addCriterion("BAN_ID not in", values, "banId");
            return (Criteria) this;
        }

        public Criteria andBanIdBetween(Long value1, Long value2) {
            addCriterion("BAN_ID between", value1, value2, "banId");
            return (Criteria) this;
        }

        public Criteria andBanIdNotBetween(Long value1, Long value2) {
            addCriterion("BAN_ID not between", value1, value2, "banId");
            return (Criteria) this;
        }

        public Criteria andBanUrlIsNull() {
            addCriterion("BAN_URL is null");
            return (Criteria) this;
        }

        public Criteria andBanUrlIsNotNull() {
            addCriterion("BAN_URL is not null");
            return (Criteria) this;
        }

        public Criteria andBanUrlEqualTo(String value) {
            addCriterion("BAN_URL =", value, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlNotEqualTo(String value) {
            addCriterion("BAN_URL <>", value, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlGreaterThan(String value) {
            addCriterion("BAN_URL >", value, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlGreaterThanOrEqualTo(String value) {
            addCriterion("BAN_URL >=", value, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlLessThan(String value) {
            addCriterion("BAN_URL <", value, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlLessThanOrEqualTo(String value) {
            addCriterion("BAN_URL <=", value, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlLike(String value) {
            addCriterion("BAN_URL like", value, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlNotLike(String value) {
            addCriterion("BAN_URL not like", value, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlIn(List<String> values) {
            addCriterion("BAN_URL in", values, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlNotIn(List<String> values) {
            addCriterion("BAN_URL not in", values, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlBetween(String value1, String value2) {
            addCriterion("BAN_URL between", value1, value2, "banUrl");
            return (Criteria) this;
        }

        public Criteria andBanUrlNotBetween(String value1, String value2) {
            addCriterion("BAN_URL not between", value1, value2, "banUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlIsNull() {
            addCriterion("JUMP_URL is null");
            return (Criteria) this;
        }

        public Criteria andJumpUrlIsNotNull() {
            addCriterion("JUMP_URL is not null");
            return (Criteria) this;
        }

        public Criteria andJumpUrlEqualTo(String value) {
            addCriterion("JUMP_URL =", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlNotEqualTo(String value) {
            addCriterion("JUMP_URL <>", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlGreaterThan(String value) {
            addCriterion("JUMP_URL >", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlGreaterThanOrEqualTo(String value) {
            addCriterion("JUMP_URL >=", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlLessThan(String value) {
            addCriterion("JUMP_URL <", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlLessThanOrEqualTo(String value) {
            addCriterion("JUMP_URL <=", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlLike(String value) {
            addCriterion("JUMP_URL like", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlNotLike(String value) {
            addCriterion("JUMP_URL not like", value, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlIn(List<String> values) {
            addCriterion("JUMP_URL in", values, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlNotIn(List<String> values) {
            addCriterion("JUMP_URL not in", values, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlBetween(String value1, String value2) {
            addCriterion("JUMP_URL between", value1, value2, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andJumpUrlNotBetween(String value1, String value2) {
            addCriterion("JUMP_URL not between", value1, value2, "jumpUrl");
            return (Criteria) this;
        }

        public Criteria andBanNameIsNull() {
            addCriterion("BAN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBanNameIsNotNull() {
            addCriterion("BAN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBanNameEqualTo(String value) {
            addCriterion("BAN_NAME =", value, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameNotEqualTo(String value) {
            addCriterion("BAN_NAME <>", value, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameGreaterThan(String value) {
            addCriterion("BAN_NAME >", value, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameGreaterThanOrEqualTo(String value) {
            addCriterion("BAN_NAME >=", value, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameLessThan(String value) {
            addCriterion("BAN_NAME <", value, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameLessThanOrEqualTo(String value) {
            addCriterion("BAN_NAME <=", value, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameLike(String value) {
            addCriterion("BAN_NAME like", value, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameNotLike(String value) {
            addCriterion("BAN_NAME not like", value, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameIn(List<String> values) {
            addCriterion("BAN_NAME in", values, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameNotIn(List<String> values) {
            addCriterion("BAN_NAME not in", values, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameBetween(String value1, String value2) {
            addCriterion("BAN_NAME between", value1, value2, "banName");
            return (Criteria) this;
        }

        public Criteria andBanNameNotBetween(String value1, String value2) {
            addCriterion("BAN_NAME not between", value1, value2, "banName");
            return (Criteria) this;
        }

        public Criteria andBanTypeIsNull() {
            addCriterion("BAN_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBanTypeIsNotNull() {
            addCriterion("BAN_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBanTypeEqualTo(String value) {
            addCriterion("BAN_TYPE =", value, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeNotEqualTo(String value) {
            addCriterion("BAN_TYPE <>", value, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeGreaterThan(String value) {
            addCriterion("BAN_TYPE >", value, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BAN_TYPE >=", value, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeLessThan(String value) {
            addCriterion("BAN_TYPE <", value, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeLessThanOrEqualTo(String value) {
            addCriterion("BAN_TYPE <=", value, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeLike(String value) {
            addCriterion("BAN_TYPE like", value, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeNotLike(String value) {
            addCriterion("BAN_TYPE not like", value, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeIn(List<String> values) {
            addCriterion("BAN_TYPE in", values, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeNotIn(List<String> values) {
            addCriterion("BAN_TYPE not in", values, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeBetween(String value1, String value2) {
            addCriterion("BAN_TYPE between", value1, value2, "banType");
            return (Criteria) this;
        }

        public Criteria andBanTypeNotBetween(String value1, String value2) {
            addCriterion("BAN_TYPE not between", value1, value2, "banType");
            return (Criteria) this;
        }

        public Criteria andReserve1IsNull() {
            addCriterion("RESERVE1 is null");
            return (Criteria) this;
        }

        public Criteria andReserve1IsNotNull() {
            addCriterion("RESERVE1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve1EqualTo(String value) {
            addCriterion("RESERVE1 =", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotEqualTo(String value) {
            addCriterion("RESERVE1 <>", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1GreaterThan(String value) {
            addCriterion("RESERVE1 >", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVE1 >=", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1LessThan(String value) {
            addCriterion("RESERVE1 <", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1LessThanOrEqualTo(String value) {
            addCriterion("RESERVE1 <=", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1Like(String value) {
            addCriterion("RESERVE1 like", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotLike(String value) {
            addCriterion("RESERVE1 not like", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1In(List<String> values) {
            addCriterion("RESERVE1 in", values, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotIn(List<String> values) {
            addCriterion("RESERVE1 not in", values, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1Between(String value1, String value2) {
            addCriterion("RESERVE1 between", value1, value2, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotBetween(String value1, String value2) {
            addCriterion("RESERVE1 not between", value1, value2, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve2IsNull() {
            addCriterion("RESERVE2 is null");
            return (Criteria) this;
        }

        public Criteria andReserve2IsNotNull() {
            addCriterion("RESERVE2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve2EqualTo(String value) {
            addCriterion("RESERVE2 =", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotEqualTo(String value) {
            addCriterion("RESERVE2 <>", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2GreaterThan(String value) {
            addCriterion("RESERVE2 >", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVE2 >=", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2LessThan(String value) {
            addCriterion("RESERVE2 <", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2LessThanOrEqualTo(String value) {
            addCriterion("RESERVE2 <=", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2Like(String value) {
            addCriterion("RESERVE2 like", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotLike(String value) {
            addCriterion("RESERVE2 not like", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2In(List<String> values) {
            addCriterion("RESERVE2 in", values, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotIn(List<String> values) {
            addCriterion("RESERVE2 not in", values, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2Between(String value1, String value2) {
            addCriterion("RESERVE2 between", value1, value2, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotBetween(String value1, String value2) {
            addCriterion("RESERVE2 not between", value1, value2, "reserve2");
            return (Criteria) this;
        }

        public Criteria andOrderSecIsNull() {
            addCriterion("ORDER_SEC is null");
            return (Criteria) this;
        }

        public Criteria andOrderSecIsNotNull() {
            addCriterion("ORDER_SEC is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSecEqualTo(Long value) {
            addCriterion("ORDER_SEC =", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecNotEqualTo(Long value) {
            addCriterion("ORDER_SEC <>", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecGreaterThan(Long value) {
            addCriterion("ORDER_SEC >", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecGreaterThanOrEqualTo(Long value) {
            addCriterion("ORDER_SEC >=", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecLessThan(Long value) {
            addCriterion("ORDER_SEC <", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecLessThanOrEqualTo(Long value) {
            addCriterion("ORDER_SEC <=", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecIn(List<Long> values) {
            addCriterion("ORDER_SEC in", values, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecNotIn(List<Long> values) {
            addCriterion("ORDER_SEC not in", values, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecBetween(Long value1, Long value2) {
            addCriterion("ORDER_SEC between", value1, value2, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecNotBetween(Long value1, Long value2) {
            addCriterion("ORDER_SEC not between", value1, value2, "orderSec");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Timestamp value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Timestamp value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_banner
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 25 15:20:22 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_banner
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}