package com.bailian.entity;

import java.sql.Timestamp;

public class Banner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.BAN_ID
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    private Long banId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.BAN_URL
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    private String banUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.JUMP_URL
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    private String jumpUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.BAN_NAME
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    private String banName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.BAN_TYPE
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    private String banType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.RESERVE1
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.RESERVE2
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.ORDER_SEC
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    private Long orderSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.STATUS
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.CREATE_TIME
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    private Timestamp createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.BAN_ID
     *
     * @return the value of t_banner.BAN_ID
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public Long getBanId() {
        return banId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.BAN_ID
     *
     * @param banId the value for t_banner.BAN_ID
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setBanId(Long banId) {
        this.banId = banId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.BAN_URL
     *
     * @return the value of t_banner.BAN_URL
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public String getBanUrl() {
        return banUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.BAN_URL
     *
     * @param banUrl the value for t_banner.BAN_URL
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setBanUrl(String banUrl) {
        this.banUrl = banUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.JUMP_URL
     *
     * @return the value of t_banner.JUMP_URL
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public String getJumpUrl() {
        return jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.JUMP_URL
     *
     * @param jumpUrl the value for t_banner.JUMP_URL
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setJumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.BAN_NAME
     *
     * @return the value of t_banner.BAN_NAME
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public String getBanName() {
        return banName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.BAN_NAME
     *
     * @param banName the value for t_banner.BAN_NAME
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setBanName(String banName) {
        this.banName = banName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.BAN_TYPE
     *
     * @return the value of t_banner.BAN_TYPE
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public String getBanType() {
        return banType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.BAN_TYPE
     *
     * @param banType the value for t_banner.BAN_TYPE
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setBanType(String banType) {
        this.banType = banType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.RESERVE1
     *
     * @return the value of t_banner.RESERVE1
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.RESERVE1
     *
     * @param reserve1 the value for t_banner.RESERVE1
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.RESERVE2
     *
     * @return the value of t_banner.RESERVE2
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.RESERVE2
     *
     * @param reserve2 the value for t_banner.RESERVE2
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.ORDER_SEC
     *
     * @return the value of t_banner.ORDER_SEC
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public Long getOrderSec() {
        return orderSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.ORDER_SEC
     *
     * @param orderSec the value for t_banner.ORDER_SEC
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setOrderSec(Long orderSec) {
        this.orderSec = orderSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.STATUS
     *
     * @return the value of t_banner.STATUS
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.STATUS
     *
     * @param status the value for t_banner.STATUS
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.CREATE_TIME
     *
     * @return the value of t_banner.CREATE_TIME
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.CREATE_TIME
     *
     * @param createTime the value for t_banner.CREATE_TIME
     *
     * @mbggenerated Sun Jun 25 15:20:22 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }
}