package com.bailian.entity;

import java.sql.Timestamp;

public class FeedBack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed_back.FEED_ID
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    private Long feedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed_back.REMARK
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed_back.MEMBER_ID
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_feed_back.CREATE_TIME
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    private Timestamp createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed_back.FEED_ID
     *
     * @return the value of t_feed_back.FEED_ID
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    public Long getFeedId() {
        return feedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed_back.FEED_ID
     *
     * @param feedId the value for t_feed_back.FEED_ID
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    public void setFeedId(Long feedId) {
        this.feedId = feedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed_back.REMARK
     *
     * @return the value of t_feed_back.REMARK
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed_back.REMARK
     *
     * @param remark the value for t_feed_back.REMARK
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed_back.MEMBER_ID
     *
     * @return the value of t_feed_back.MEMBER_ID
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed_back.MEMBER_ID
     *
     * @param memberId the value for t_feed_back.MEMBER_ID
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_feed_back.CREATE_TIME
     *
     * @return the value of t_feed_back.CREATE_TIME
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_feed_back.CREATE_TIME
     *
     * @param createTime the value for t_feed_back.CREATE_TIME
     *
     * @mbggenerated Sun May 28 09:31:50 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }
}