package com.bailian.entity;

import java.sql.Timestamp;

public class GoodsRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_record.RECORD_ID
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    private Long recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_record.MEMBER_ID
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_record.GOODS_ID
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_record.GOODS_NAME
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_record.GOODS_POINTS
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    private Long goodsPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_record.GOODS_NUM
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    private Long goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_record.CREATE_TIME
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_record.GOODS_PIC
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    private String goodsPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_record.GOODS_TYPE
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    private String goodsType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_record.RECORD_ID
     *
     * @return the value of t_goods_record.RECORD_ID
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_record.RECORD_ID
     *
     * @param recordId the value for t_goods_record.RECORD_ID
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_record.MEMBER_ID
     *
     * @return the value of t_goods_record.MEMBER_ID
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_record.MEMBER_ID
     *
     * @param memberId the value for t_goods_record.MEMBER_ID
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_record.GOODS_ID
     *
     * @return the value of t_goods_record.GOODS_ID
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_record.GOODS_ID
     *
     * @param goodsId the value for t_goods_record.GOODS_ID
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_record.GOODS_NAME
     *
     * @return the value of t_goods_record.GOODS_NAME
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_record.GOODS_NAME
     *
     * @param goodsName the value for t_goods_record.GOODS_NAME
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_record.GOODS_POINTS
     *
     * @return the value of t_goods_record.GOODS_POINTS
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public Long getGoodsPoints() {
        return goodsPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_record.GOODS_POINTS
     *
     * @param goodsPoints the value for t_goods_record.GOODS_POINTS
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public void setGoodsPoints(Long goodsPoints) {
        this.goodsPoints = goodsPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_record.GOODS_NUM
     *
     * @return the value of t_goods_record.GOODS_NUM
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public Long getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_record.GOODS_NUM
     *
     * @param goodsNum the value for t_goods_record.GOODS_NUM
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public void setGoodsNum(Long goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_record.CREATE_TIME
     *
     * @return the value of t_goods_record.CREATE_TIME
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_record.CREATE_TIME
     *
     * @param createTime the value for t_goods_record.CREATE_TIME
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_record.GOODS_PIC
     *
     * @return the value of t_goods_record.GOODS_PIC
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_record.GOODS_PIC
     *
     * @param goodsPic the value for t_goods_record.GOODS_PIC
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_record.GOODS_TYPE
     *
     * @return the value of t_goods_record.GOODS_TYPE
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_record.GOODS_TYPE
     *
     * @param goodsType the value for t_goods_record.GOODS_TYPE
     *
     * @mbggenerated Mon Nov 20 16:53:12 CST 2017
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType;
    }
}