package com.bailian.entity;

import java.sql.Timestamp;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GOODS.GOODS_ID
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GOODS.GOODS_NAME
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GOODS.GOODS_POINTS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    private Long goodsPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GOODS.CREATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GOODS.UPDATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    private Timestamp updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GOODS.APP_PIC_URL
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    private String appPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GOODS.PC_PIC_URL
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    private String pcPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GOODS.IS_DELETE
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GOODS.GOODS_ID
     *
     * @return the value of T_GOODS.GOODS_ID
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GOODS.GOODS_ID
     *
     * @param goodsId the value for T_GOODS.GOODS_ID
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GOODS.GOODS_NAME
     *
     * @return the value of T_GOODS.GOODS_NAME
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GOODS.GOODS_NAME
     *
     * @param goodsName the value for T_GOODS.GOODS_NAME
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GOODS.GOODS_POINTS
     *
     * @return the value of T_GOODS.GOODS_POINTS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public Long getGoodsPoints() {
        return goodsPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GOODS.GOODS_POINTS
     *
     * @param goodsPoints the value for T_GOODS.GOODS_POINTS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void setGoodsPoints(Long goodsPoints) {
        this.goodsPoints = goodsPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GOODS.CREATE_TIME
     *
     * @return the value of T_GOODS.CREATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GOODS.CREATE_TIME
     *
     * @param createTime the value for T_GOODS.CREATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GOODS.UPDATE_TIME
     *
     * @return the value of T_GOODS.UPDATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GOODS.UPDATE_TIME
     *
     * @param updateTime the value for T_GOODS.UPDATE_TIME
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GOODS.APP_PIC_URL
     *
     * @return the value of T_GOODS.APP_PIC_URL
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public String getAppPicUrl() {
        return appPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GOODS.APP_PIC_URL
     *
     * @param appPicUrl the value for T_GOODS.APP_PIC_URL
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void setAppPicUrl(String appPicUrl) {
        this.appPicUrl = appPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GOODS.PC_PIC_URL
     *
     * @return the value of T_GOODS.PC_PIC_URL
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public String getPcPicUrl() {
        return pcPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GOODS.PC_PIC_URL
     *
     * @param pcPicUrl the value for T_GOODS.PC_PIC_URL
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void setPcPicUrl(String pcPicUrl) {
        this.pcPicUrl = pcPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GOODS.IS_DELETE
     *
     * @return the value of T_GOODS.IS_DELETE
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GOODS.IS_DELETE
     *
     * @param isDelete the value for T_GOODS.IS_DELETE
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
}