package com.bailian.entity;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class GoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public GoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("GOODS_ID is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("GOODS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Long value) {
            addCriterion("GOODS_ID =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Long value) {
            addCriterion("GOODS_ID <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Long value) {
            addCriterion("GOODS_ID >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("GOODS_ID >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Long value) {
            addCriterion("GOODS_ID <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Long value) {
            addCriterion("GOODS_ID <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Long> values) {
            addCriterion("GOODS_ID in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Long> values) {
            addCriterion("GOODS_ID not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Long value1, Long value2) {
            addCriterion("GOODS_ID between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Long value1, Long value2) {
            addCriterion("GOODS_ID not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("GOODS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("GOODS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("GOODS_NAME =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("GOODS_NAME <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("GOODS_NAME >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("GOODS_NAME >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("GOODS_NAME <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("GOODS_NAME <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("GOODS_NAME like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("GOODS_NAME not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("GOODS_NAME in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("GOODS_NAME not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("GOODS_NAME between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("GOODS_NAME not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsIsNull() {
            addCriterion("GOODS_POINTS is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsIsNotNull() {
            addCriterion("GOODS_POINTS is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsEqualTo(Long value) {
            addCriterion("GOODS_POINTS =", value, "goodsPoints");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsNotEqualTo(Long value) {
            addCriterion("GOODS_POINTS <>", value, "goodsPoints");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsGreaterThan(Long value) {
            addCriterion("GOODS_POINTS >", value, "goodsPoints");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsGreaterThanOrEqualTo(Long value) {
            addCriterion("GOODS_POINTS >=", value, "goodsPoints");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsLessThan(Long value) {
            addCriterion("GOODS_POINTS <", value, "goodsPoints");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsLessThanOrEqualTo(Long value) {
            addCriterion("GOODS_POINTS <=", value, "goodsPoints");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsIn(List<Long> values) {
            addCriterion("GOODS_POINTS in", values, "goodsPoints");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsNotIn(List<Long> values) {
            addCriterion("GOODS_POINTS not in", values, "goodsPoints");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsBetween(Long value1, Long value2) {
            addCriterion("GOODS_POINTS between", value1, value2, "goodsPoints");
            return (Criteria) this;
        }

        public Criteria andGoodsPointsNotBetween(Long value1, Long value2) {
            addCriterion("GOODS_POINTS not between", value1, value2, "goodsPoints");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Timestamp value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Timestamp value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Timestamp value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Timestamp value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Timestamp> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Timestamp> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlIsNull() {
            addCriterion("APP_PIC_URL is null");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlIsNotNull() {
            addCriterion("APP_PIC_URL is not null");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlEqualTo(String value) {
            addCriterion("APP_PIC_URL =", value, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlNotEqualTo(String value) {
            addCriterion("APP_PIC_URL <>", value, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlGreaterThan(String value) {
            addCriterion("APP_PIC_URL >", value, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("APP_PIC_URL >=", value, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlLessThan(String value) {
            addCriterion("APP_PIC_URL <", value, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlLessThanOrEqualTo(String value) {
            addCriterion("APP_PIC_URL <=", value, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlLike(String value) {
            addCriterion("APP_PIC_URL like", value, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlNotLike(String value) {
            addCriterion("APP_PIC_URL not like", value, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlIn(List<String> values) {
            addCriterion("APP_PIC_URL in", values, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlNotIn(List<String> values) {
            addCriterion("APP_PIC_URL not in", values, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlBetween(String value1, String value2) {
            addCriterion("APP_PIC_URL between", value1, value2, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andAppPicUrlNotBetween(String value1, String value2) {
            addCriterion("APP_PIC_URL not between", value1, value2, "appPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlIsNull() {
            addCriterion("PC_PIC_URL is null");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlIsNotNull() {
            addCriterion("PC_PIC_URL is not null");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlEqualTo(String value) {
            addCriterion("PC_PIC_URL =", value, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlNotEqualTo(String value) {
            addCriterion("PC_PIC_URL <>", value, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlGreaterThan(String value) {
            addCriterion("PC_PIC_URL >", value, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PC_PIC_URL >=", value, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlLessThan(String value) {
            addCriterion("PC_PIC_URL <", value, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlLessThanOrEqualTo(String value) {
            addCriterion("PC_PIC_URL <=", value, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlLike(String value) {
            addCriterion("PC_PIC_URL like", value, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlNotLike(String value) {
            addCriterion("PC_PIC_URL not like", value, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlIn(List<String> values) {
            addCriterion("PC_PIC_URL in", values, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlNotIn(List<String> values) {
            addCriterion("PC_PIC_URL not in", values, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlBetween(String value1, String value2) {
            addCriterion("PC_PIC_URL between", value1, value2, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andPcPicUrlNotBetween(String value1, String value2) {
            addCriterion("PC_PIC_URL not between", value1, value2, "pcPicUrl");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(String value) {
            addCriterion("IS_DELETE =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(String value) {
            addCriterion("IS_DELETE <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(String value) {
            addCriterion("IS_DELETE >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETE >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(String value) {
            addCriterion("IS_DELETE <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETE <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLike(String value) {
            addCriterion("IS_DELETE like", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotLike(String value) {
            addCriterion("IS_DELETE not like", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<String> values) {
            addCriterion("IS_DELETE in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<String> values) {
            addCriterion("IS_DELETE not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(String value1, String value2) {
            addCriterion("IS_DELETE between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(String value1, String value2) {
            addCriterion("IS_DELETE not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_GOODS
     *
     * @mbggenerated do_not_delete_during_merge Mon May 22 20:03:22 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_GOODS
     *
     * @mbggenerated Mon May 22 20:03:22 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}