package com.bailian.entity;

import java.sql.Timestamp;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.ORDER_ID
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.POINTS
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    private Long points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.MEMBER_ID
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.RULE_ID
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    private Long ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_info.CREATE_TIME
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    private Timestamp createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.ORDER_ID
     *
     * @return the value of t_order_info.ORDER_ID
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.ORDER_ID
     *
     * @param orderId the value for t_order_info.ORDER_ID
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.POINTS
     *
     * @return the value of t_order_info.POINTS
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    public Long getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.POINTS
     *
     * @param points the value for t_order_info.POINTS
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    public void setPoints(Long points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.MEMBER_ID
     *
     * @return the value of t_order_info.MEMBER_ID
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.MEMBER_ID
     *
     * @param memberId the value for t_order_info.MEMBER_ID
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.RULE_ID
     *
     * @return the value of t_order_info.RULE_ID
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.RULE_ID
     *
     * @param ruleId the value for t_order_info.RULE_ID
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_info.CREATE_TIME
     *
     * @return the value of t_order_info.CREATE_TIME
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_info.CREATE_TIME
     *
     * @param createTime the value for t_order_info.CREATE_TIME
     *
     * @mbggenerated Fri Jun 02 22:22:04 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }
}