package com.bailian.entity;

import java.sql.Timestamp;

public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.DETAIL_ID
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    private Long detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.ORDER_ID
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.GOODS_ID
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.GOODS_NUM
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    private Long goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.GOODS_POINTS
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    private Long goodsPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.GOODS_NAME
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.CREATE_TIME
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    private Timestamp createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.DETAIL_ID
     *
     * @return the value of t_order_detail.DETAIL_ID
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public Long getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.DETAIL_ID
     *
     * @param detailId the value for t_order_detail.DETAIL_ID
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.ORDER_ID
     *
     * @return the value of t_order_detail.ORDER_ID
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.ORDER_ID
     *
     * @param orderId the value for t_order_detail.ORDER_ID
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.GOODS_ID
     *
     * @return the value of t_order_detail.GOODS_ID
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.GOODS_ID
     *
     * @param goodsId the value for t_order_detail.GOODS_ID
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.GOODS_NUM
     *
     * @return the value of t_order_detail.GOODS_NUM
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public Long getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.GOODS_NUM
     *
     * @param goodsNum the value for t_order_detail.GOODS_NUM
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public void setGoodsNum(Long goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.GOODS_POINTS
     *
     * @return the value of t_order_detail.GOODS_POINTS
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public Long getGoodsPoints() {
        return goodsPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.GOODS_POINTS
     *
     * @param goodsPoints the value for t_order_detail.GOODS_POINTS
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public void setGoodsPoints(Long goodsPoints) {
        this.goodsPoints = goodsPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.GOODS_NAME
     *
     * @return the value of t_order_detail.GOODS_NAME
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.GOODS_NAME
     *
     * @param goodsName the value for t_order_detail.GOODS_NAME
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.CREATE_TIME
     *
     * @return the value of t_order_detail.CREATE_TIME
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.CREATE_TIME
     *
     * @param createTime the value for t_order_detail.CREATE_TIME
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }
}