package com.bailian.entity;

import java.sql.Timestamp;

public class PointsRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_points_record.RECORD_ID
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    private Long recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_points_record.FROM_MEM
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    private String fromMem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_points_record.TO_MEM
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    private String toMem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_points_record.POINTS
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    private String points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_points_record.RESERVE1
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_points_record.RESERVE2
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_points_record.CREATE_TIME
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    private Timestamp createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_points_record.RECORD_ID
     *
     * @return the value of t_points_record.RECORD_ID
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_points_record.RECORD_ID
     *
     * @param recordId the value for t_points_record.RECORD_ID
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_points_record.FROM_MEM
     *
     * @return the value of t_points_record.FROM_MEM
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public String getFromMem() {
        return fromMem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_points_record.FROM_MEM
     *
     * @param fromMem the value for t_points_record.FROM_MEM
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public void setFromMem(String fromMem) {
        this.fromMem = fromMem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_points_record.TO_MEM
     *
     * @return the value of t_points_record.TO_MEM
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public String getToMem() {
        return toMem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_points_record.TO_MEM
     *
     * @param toMem the value for t_points_record.TO_MEM
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public void setToMem(String toMem) {
        this.toMem = toMem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_points_record.POINTS
     *
     * @return the value of t_points_record.POINTS
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public String getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_points_record.POINTS
     *
     * @param points the value for t_points_record.POINTS
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public void setPoints(String points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_points_record.RESERVE1
     *
     * @return the value of t_points_record.RESERVE1
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_points_record.RESERVE1
     *
     * @param reserve1 the value for t_points_record.RESERVE1
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_points_record.RESERVE2
     *
     * @return the value of t_points_record.RESERVE2
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_points_record.RESERVE2
     *
     * @param reserve2 the value for t_points_record.RESERVE2
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_points_record.CREATE_TIME
     *
     * @return the value of t_points_record.CREATE_TIME
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_points_record.CREATE_TIME
     *
     * @param createTime the value for t_points_record.CREATE_TIME
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }
}