package com.bailian.entity;

import java.sql.Timestamp;

public class RuleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rule_info.RULE_ID
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    private Long ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rule_info.RULE_NAME
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    private String ruleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rule_info.DAY_POINTS
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    private Long dayPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rule_info.FIRST_RATE
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    private Long firstRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rule_info.SEC_RATE
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    private Long secRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rule_info.STATUS
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rule_info.CREATE_TIME
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rule_info.UPDATE_TIME
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    private Timestamp updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rule_info.RULE_ID
     *
     * @return the value of t_rule_info.RULE_ID
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rule_info.RULE_ID
     *
     * @param ruleId the value for t_rule_info.RULE_ID
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rule_info.RULE_NAME
     *
     * @return the value of t_rule_info.RULE_NAME
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rule_info.RULE_NAME
     *
     * @param ruleName the value for t_rule_info.RULE_NAME
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rule_info.DAY_POINTS
     *
     * @return the value of t_rule_info.DAY_POINTS
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public Long getDayPoints() {
        return dayPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rule_info.DAY_POINTS
     *
     * @param dayPoints the value for t_rule_info.DAY_POINTS
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public void setDayPoints(Long dayPoints) {
        this.dayPoints = dayPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rule_info.FIRST_RATE
     *
     * @return the value of t_rule_info.FIRST_RATE
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public Long getFirstRate() {
        return firstRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rule_info.FIRST_RATE
     *
     * @param firstRate the value for t_rule_info.FIRST_RATE
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public void setFirstRate(Long firstRate) {
        this.firstRate = firstRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rule_info.SEC_RATE
     *
     * @return the value of t_rule_info.SEC_RATE
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public Long getSecRate() {
        return secRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rule_info.SEC_RATE
     *
     * @param secRate the value for t_rule_info.SEC_RATE
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public void setSecRate(Long secRate) {
        this.secRate = secRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rule_info.STATUS
     *
     * @return the value of t_rule_info.STATUS
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rule_info.STATUS
     *
     * @param status the value for t_rule_info.STATUS
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rule_info.CREATE_TIME
     *
     * @return the value of t_rule_info.CREATE_TIME
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rule_info.CREATE_TIME
     *
     * @param createTime the value for t_rule_info.CREATE_TIME
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rule_info.UPDATE_TIME
     *
     * @return the value of t_rule_info.UPDATE_TIME
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rule_info.UPDATE_TIME
     *
     * @param updateTime the value for t_rule_info.UPDATE_TIME
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }
}