package com.bailian.entity;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class SelectedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public SelectedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSelIdIsNull() {
            addCriterion("SEL_ID is null");
            return (Criteria) this;
        }

        public Criteria andSelIdIsNotNull() {
            addCriterion("SEL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSelIdEqualTo(Long value) {
            addCriterion("SEL_ID =", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdNotEqualTo(Long value) {
            addCriterion("SEL_ID <>", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdGreaterThan(Long value) {
            addCriterion("SEL_ID >", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SEL_ID >=", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdLessThan(Long value) {
            addCriterion("SEL_ID <", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdLessThanOrEqualTo(Long value) {
            addCriterion("SEL_ID <=", value, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdIn(List<Long> values) {
            addCriterion("SEL_ID in", values, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdNotIn(List<Long> values) {
            addCriterion("SEL_ID not in", values, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdBetween(Long value1, Long value2) {
            addCriterion("SEL_ID between", value1, value2, "selId");
            return (Criteria) this;
        }

        public Criteria andSelIdNotBetween(Long value1, Long value2) {
            addCriterion("SEL_ID not between", value1, value2, "selId");
            return (Criteria) this;
        }

        public Criteria andSelNameIsNull() {
            addCriterion("SEL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSelNameIsNotNull() {
            addCriterion("SEL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSelNameEqualTo(String value) {
            addCriterion("SEL_NAME =", value, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameNotEqualTo(String value) {
            addCriterion("SEL_NAME <>", value, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameGreaterThan(String value) {
            addCriterion("SEL_NAME >", value, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameGreaterThanOrEqualTo(String value) {
            addCriterion("SEL_NAME >=", value, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameLessThan(String value) {
            addCriterion("SEL_NAME <", value, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameLessThanOrEqualTo(String value) {
            addCriterion("SEL_NAME <=", value, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameLike(String value) {
            addCriterion("SEL_NAME like", value, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameNotLike(String value) {
            addCriterion("SEL_NAME not like", value, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameIn(List<String> values) {
            addCriterion("SEL_NAME in", values, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameNotIn(List<String> values) {
            addCriterion("SEL_NAME not in", values, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameBetween(String value1, String value2) {
            addCriterion("SEL_NAME between", value1, value2, "selName");
            return (Criteria) this;
        }

        public Criteria andSelNameNotBetween(String value1, String value2) {
            addCriterion("SEL_NAME not between", value1, value2, "selName");
            return (Criteria) this;
        }

        public Criteria andSelTypeIsNull() {
            addCriterion("SEL_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSelTypeIsNotNull() {
            addCriterion("SEL_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSelTypeEqualTo(String value) {
            addCriterion("SEL_TYPE =", value, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeNotEqualTo(String value) {
            addCriterion("SEL_TYPE <>", value, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeGreaterThan(String value) {
            addCriterion("SEL_TYPE >", value, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SEL_TYPE >=", value, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeLessThan(String value) {
            addCriterion("SEL_TYPE <", value, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeLessThanOrEqualTo(String value) {
            addCriterion("SEL_TYPE <=", value, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeLike(String value) {
            addCriterion("SEL_TYPE like", value, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeNotLike(String value) {
            addCriterion("SEL_TYPE not like", value, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeIn(List<String> values) {
            addCriterion("SEL_TYPE in", values, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeNotIn(List<String> values) {
            addCriterion("SEL_TYPE not in", values, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeBetween(String value1, String value2) {
            addCriterion("SEL_TYPE between", value1, value2, "selType");
            return (Criteria) this;
        }

        public Criteria andSelTypeNotBetween(String value1, String value2) {
            addCriterion("SEL_TYPE not between", value1, value2, "selType");
            return (Criteria) this;
        }

        public Criteria andSelPriceIsNull() {
            addCriterion("SEL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andSelPriceIsNotNull() {
            addCriterion("SEL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andSelPriceEqualTo(String value) {
            addCriterion("SEL_PRICE =", value, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceNotEqualTo(String value) {
            addCriterion("SEL_PRICE <>", value, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceGreaterThan(String value) {
            addCriterion("SEL_PRICE >", value, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceGreaterThanOrEqualTo(String value) {
            addCriterion("SEL_PRICE >=", value, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceLessThan(String value) {
            addCriterion("SEL_PRICE <", value, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceLessThanOrEqualTo(String value) {
            addCriterion("SEL_PRICE <=", value, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceLike(String value) {
            addCriterion("SEL_PRICE like", value, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceNotLike(String value) {
            addCriterion("SEL_PRICE not like", value, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceIn(List<String> values) {
            addCriterion("SEL_PRICE in", values, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceNotIn(List<String> values) {
            addCriterion("SEL_PRICE not in", values, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceBetween(String value1, String value2) {
            addCriterion("SEL_PRICE between", value1, value2, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPriceNotBetween(String value1, String value2) {
            addCriterion("SEL_PRICE not between", value1, value2, "selPrice");
            return (Criteria) this;
        }

        public Criteria andSelPicsIsNull() {
            addCriterion("SEL_PICS is null");
            return (Criteria) this;
        }

        public Criteria andSelPicsIsNotNull() {
            addCriterion("SEL_PICS is not null");
            return (Criteria) this;
        }

        public Criteria andSelPicsEqualTo(String value) {
            addCriterion("SEL_PICS =", value, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsNotEqualTo(String value) {
            addCriterion("SEL_PICS <>", value, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsGreaterThan(String value) {
            addCriterion("SEL_PICS >", value, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsGreaterThanOrEqualTo(String value) {
            addCriterion("SEL_PICS >=", value, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsLessThan(String value) {
            addCriterion("SEL_PICS <", value, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsLessThanOrEqualTo(String value) {
            addCriterion("SEL_PICS <=", value, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsLike(String value) {
            addCriterion("SEL_PICS like", value, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsNotLike(String value) {
            addCriterion("SEL_PICS not like", value, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsIn(List<String> values) {
            addCriterion("SEL_PICS in", values, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsNotIn(List<String> values) {
            addCriterion("SEL_PICS not in", values, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsBetween(String value1, String value2) {
            addCriterion("SEL_PICS between", value1, value2, "selPics");
            return (Criteria) this;
        }

        public Criteria andSelPicsNotBetween(String value1, String value2) {
            addCriterion("SEL_PICS not between", value1, value2, "selPics");
            return (Criteria) this;
        }

        public Criteria andOrderSecIsNull() {
            addCriterion("ORDER_SEC is null");
            return (Criteria) this;
        }

        public Criteria andOrderSecIsNotNull() {
            addCriterion("ORDER_SEC is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSecEqualTo(Long value) {
            addCriterion("ORDER_SEC =", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecNotEqualTo(Long value) {
            addCriterion("ORDER_SEC <>", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecGreaterThan(Long value) {
            addCriterion("ORDER_SEC >", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecGreaterThanOrEqualTo(Long value) {
            addCriterion("ORDER_SEC >=", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecLessThan(Long value) {
            addCriterion("ORDER_SEC <", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecLessThanOrEqualTo(Long value) {
            addCriterion("ORDER_SEC <=", value, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecIn(List<Long> values) {
            addCriterion("ORDER_SEC in", values, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecNotIn(List<Long> values) {
            addCriterion("ORDER_SEC not in", values, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecBetween(Long value1, Long value2) {
            addCriterion("ORDER_SEC between", value1, value2, "orderSec");
            return (Criteria) this;
        }

        public Criteria andOrderSecNotBetween(Long value1, Long value2) {
            addCriterion("ORDER_SEC not between", value1, value2, "orderSec");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andReserve1IsNull() {
            addCriterion("RESERVE1 is null");
            return (Criteria) this;
        }

        public Criteria andReserve1IsNotNull() {
            addCriterion("RESERVE1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve1EqualTo(String value) {
            addCriterion("RESERVE1 =", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotEqualTo(String value) {
            addCriterion("RESERVE1 <>", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1GreaterThan(String value) {
            addCriterion("RESERVE1 >", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVE1 >=", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1LessThan(String value) {
            addCriterion("RESERVE1 <", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1LessThanOrEqualTo(String value) {
            addCriterion("RESERVE1 <=", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1Like(String value) {
            addCriterion("RESERVE1 like", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotLike(String value) {
            addCriterion("RESERVE1 not like", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1In(List<String> values) {
            addCriterion("RESERVE1 in", values, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotIn(List<String> values) {
            addCriterion("RESERVE1 not in", values, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1Between(String value1, String value2) {
            addCriterion("RESERVE1 between", value1, value2, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotBetween(String value1, String value2) {
            addCriterion("RESERVE1 not between", value1, value2, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve2IsNull() {
            addCriterion("RESERVE2 is null");
            return (Criteria) this;
        }

        public Criteria andReserve2IsNotNull() {
            addCriterion("RESERVE2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve2EqualTo(String value) {
            addCriterion("RESERVE2 =", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotEqualTo(String value) {
            addCriterion("RESERVE2 <>", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2GreaterThan(String value) {
            addCriterion("RESERVE2 >", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2GreaterThanOrEqualTo(String value) {
            addCriterion("RESERVE2 >=", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2LessThan(String value) {
            addCriterion("RESERVE2 <", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2LessThanOrEqualTo(String value) {
            addCriterion("RESERVE2 <=", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2Like(String value) {
            addCriterion("RESERVE2 like", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotLike(String value) {
            addCriterion("RESERVE2 not like", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2In(List<String> values) {
            addCriterion("RESERVE2 in", values, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotIn(List<String> values) {
            addCriterion("RESERVE2 not in", values, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2Between(String value1, String value2) {
            addCriterion("RESERVE2 between", value1, value2, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotBetween(String value1, String value2) {
            addCriterion("RESERVE2 not between", value1, value2, "reserve2");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Timestamp value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Timestamp value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_selected
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 17 15:04:20 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_selected
     *
     * @mbggenerated Fri Nov 17 15:04:20 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}