package com.bailian.persistence;

import com.bailian.dto.ActivityDetailDto;
import com.bailian.entity.ActivityDetail;
import com.bailian.entity.ActivityDetailExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ActivityDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    int countByExample(ActivityDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    int deleteByExample(ActivityDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    int deleteByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    int insert(ActivityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    int insertSelective(ActivityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    List<ActivityDetail> selectByExample(ActivityDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    ActivityDetail selectByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") ActivityDetail record, @Param("example") ActivityDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    int updateByExample(@Param("record") ActivityDetail record, @Param("example") ActivityDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    int updateByPrimaryKeySelective(ActivityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY_DETAIL
     *
     * @mbggenerated Sat May 20 23:23:00 CST 2017
     */
    int updateByPrimaryKey(ActivityDetail record);
    
    

    /**
     * ªÒ»°œÍ«È
     * @param actId
     * @return
     */
    public List<ActivityDetailDto> getActDetailList(Long actId);
}