package com.bailian.persistence;

import com.bailian.dto.ActivityDto;
import com.bailian.entity.Activity;
import com.bailian.entity.ActivityExample;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    int countByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    int deleteByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    int deleteByPrimaryKey(Long actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    List<Activity> selectByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    Activity selectByPrimaryKey(Long actId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    int updateByExample(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ACTIVITY
     *
     * @mbggenerated Sat May 20 20:41:20 CST 2017
     */
    int updateByPrimaryKey(Activity record);
    
    
    
    /**
     * 分页查询
     * @param paraMap
     * @return
     */
    public List<ActivityDto> selActivityByPage(Map<String, Object> paraMap);

	/**
	 * 查询运行的抽奖和兑换
	 * @return
	 */
	public Activity getRunningAct(String type);
	
	/**
	 * 校验时间有效
	 * @param map
	 * @return
	 */
	public Long checkActTime(Map<String, Object> map);

	/**
	 * 积分兑换活动查询
	 * @param map
	 * @return
	 */
	List<ActivityDto> selExchangeByPage(Map<String, Object> map);
	
	
	
}