package com.bailian.persistence;

import com.bailian.dto.AwardsRecordDto;
import com.bailian.entity.AwardsRecord;
import com.bailian.entity.AwardsRecordExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface AwardsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    int countByExample(AwardsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    int deleteByExample(AwardsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    int insert(AwardsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    int insertSelective(AwardsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    List<AwardsRecord> selectByExample(AwardsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    AwardsRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") AwardsRecord record, @Param("example") AwardsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    int updateByExample(@Param("record") AwardsRecord record, @Param("example") AwardsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    int updateByPrimaryKeySelective(AwardsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_AWARDS_RECORD
     *
     * @mbggenerated Sun May 21 14:58:22 CST 2017
     */
    int updateByPrimaryKey(AwardsRecord record);

    /**
     * ∑÷“≥≤È—Ø
     * @param map
     * @return
     */
	int countAwards(Map<String, Object> map);

	/**
	 * ∑÷“≥
	 * @param map
	 * @return
	 */
	List<AwardsRecordDto> selAwardsByPage(Map<String, Object> map);
}