package com.bailian.persistence;

import com.bailian.dto.GoodsRecordDto;
import com.bailian.entity.GoodsRecord;
import com.bailian.entity.GoodsRecordExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface GoodsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    int countByExample(GoodsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    int deleteByExample(GoodsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    int insert(GoodsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    int insertSelective(GoodsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    List<GoodsRecord> selectByExample(GoodsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    GoodsRecord selectByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") GoodsRecord record, @Param("example") GoodsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    int updateByExample(@Param("record") GoodsRecord record, @Param("example") GoodsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    int updateByPrimaryKeySelective(GoodsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS_RECORD
     *
     * @mbggenerated Wed May 17 20:10:28 CST 2017
     */
    int updateByPrimaryKey(GoodsRecord record);
    
    //下面是自己定义的mapper

    /**
     * 查询兑换数量
     * @param paraMap
     * @return
     */
	Integer countExchange(Map<String, Object> paraMap);

	/**
	 * 查询兑换记录列表
	 * @param paraMap
	 * @return
	 */
	List<GoodsRecordDto> selExchangeList(Map<String, Object> paraMap);
}