package com.bailian.persistence;

import com.bailian.entity.Goods;
import com.bailian.entity.GoodsExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    int countByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    int deleteByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    int deleteByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    List<Goods> selectByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    Goods selectByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    int updateByExample(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GOODS
     *
     * @mbggenerated Wed May 17 20:10:24 CST 2017
     */
    int updateByPrimaryKey(Goods record);

    
    
	List<Goods> selGoodsPage(Map<String, Object> paraMap);
}