package com.bailian.persistence;

import com.bailian.entity.MemberInfo;
import com.bailian.entity.MemberInfoExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MemberInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    int countByExample(MemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    int deleteByExample(MemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    int insert(MemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    int insertSelective(MemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    List<MemberInfo> selectByExample(MemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    MemberInfo selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") MemberInfo record, @Param("example") MemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    int updateByExample(@Param("record") MemberInfo record, @Param("example") MemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    int updateByPrimaryKeySelective(MemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_info
     *
     * @mbggenerated Fri Jun 02 22:08:59 CST 2017
     */
    int updateByPrimaryKey(MemberInfo record);
    
    
    

    List<MemberInfo> selMemberByPage(Map<String, Object> paMap);
     
     /**
      * 登陆送积分
      * @param memberId
      */
    public void LoginSendPoints(@Param("memberId")Long memberId,@Param("points")Long Points);
    
    /**
     * 增加推荐人积分
     * @param mobile
     * @param points
     */
    public void addMemPointsByMobile(@Param("mobile")String mobile,@Param("points")Long points);

    
    /**
     * 根据手机号查人
     * @param mobile
     * @return
     */
    MemberInfo selectByMobile(String mobile);

    /**
     * 增加推荐人次数
     * @param referTo
     */
	public void addReferToNum(String referTo);

}