package com.bailian.persistence;

import com.bailian.entity.OrderDetail;
import com.bailian.entity.OrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    int countByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    int deleteByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    int deleteByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    OrderDetail selectByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    int updateByExample(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated Sat Jun 03 11:20:07 CST 2017
     */
    int updateByPrimaryKey(OrderDetail record);
}