package com.bailian.persistence;

import com.bailian.entity.PointsRecord;
import com.bailian.entity.PointsRecordExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PointsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    int countByExample(PointsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    int deleteByExample(PointsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    int deleteByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    int insert(PointsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    int insertSelective(PointsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    List<PointsRecord> selectByExample(PointsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    PointsRecord selectByPrimaryKey(Long recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") PointsRecord record, @Param("example") PointsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    int updateByExample(@Param("record") PointsRecord record, @Param("example") PointsRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    int updateByPrimaryKeySelective(PointsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_points_record
     *
     * @mbggenerated Thu Jun 29 10:20:25 CST 2017
     */
    int updateByPrimaryKey(PointsRecord record);
    
    
    List<PointsRecord> selPointsRecordByPage(Map<String, Object> map);
}