package com.bailian.persistence;

import com.bailian.entity.RuleInfo;
import com.bailian.entity.RuleInfoExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RuleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    int countByExample(RuleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    int deleteByExample(RuleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    int deleteByPrimaryKey(Long ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    int insert(RuleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    int insertSelective(RuleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    List<RuleInfo> selectByExample(RuleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    RuleInfo selectByPrimaryKey(Long ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    int updateByExampleSelective(@Param("record") RuleInfo record, @Param("example") RuleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    int updateByExample(@Param("record") RuleInfo record, @Param("example") RuleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    int updateByPrimaryKeySelective(RuleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rule_info
     *
     * @mbggenerated Fri Jun 02 22:25:46 CST 2017
     */
    int updateByPrimaryKey(RuleInfo record);
    
    /**
     * ∑÷“≥≤È—Ø
     * @param map
     * @return
     */
    List<RuleInfo> selRuleByPage(Map<String, Object> map);
}